-- GTM (Prospecting + Outreach) becomes ONE plugin. Guarded copy per table.
-- DDL comes from REPLAYING schema.sql + all migrations (base CREATEs lag the
-- live shape because of later ALTERs); explicit column lists on both sides of
-- the copy so a column-count drift can never mis-map values.
CREATE TABLE IF NOT EXISTS gtm_api_quota (provider TEXT PRIMARY KEY, payload TEXT NOT NULL, captured_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_api_quota (provider TEXT PRIMARY KEY, payload TEXT NOT NULL, captured_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_api_quota (provider, payload, captured_at) SELECT provider, payload, captured_at FROM gtm_api_quota;
DROP TABLE gtm_api_quota;
CREATE TABLE IF NOT EXISTS gtm_api_usage (provider TEXT NOT NULL, period TEXT NOT NULL, used INTEGER NOT NULL DEFAULT 0, warned_at INTEGER, updated_at INTEGER NOT NULL, PRIMARY KEY (provider, period));
CREATE TABLE IF NOT EXISTS plugin_gtm_api_usage (provider TEXT NOT NULL, period TEXT NOT NULL, used INTEGER NOT NULL DEFAULT 0, warned_at INTEGER, updated_at INTEGER NOT NULL, PRIMARY KEY (provider, period));
INSERT OR IGNORE INTO plugin_gtm_api_usage (provider, period, used, warned_at, updated_at) SELECT provider, period, used, warned_at, updated_at FROM gtm_api_usage;
DROP TABLE gtm_api_usage;
CREATE TABLE IF NOT EXISTS gtm_batches (id TEXT PRIMARY KEY, source TEXT, via TEXT, total INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL DEFAULT 0, duplicates INTEGER NOT NULL DEFAULT 0, invalid INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_batches (id TEXT PRIMARY KEY, source TEXT, via TEXT, total INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL DEFAULT 0, duplicates INTEGER NOT NULL DEFAULT 0, invalid INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_batches (id, source, via, total, created, duplicates, invalid, created_at) SELECT id, source, via, total, created, duplicates, invalid, created_at FROM gtm_batches;
DROP TABLE gtm_batches;
CREATE TABLE IF NOT EXISTS gtm_leads (id TEXT PRIMARY KEY, phone TEXT NOT NULL, normalized_phone TEXT, status TEXT NOT NULL DEFAULT 'new', source TEXT, batch_id TEXT, country TEXT, region TEXT, name TEXT, photo TEXT, socials TEXT NOT NULL DEFAULT '[]', linkedin TEXT, email TEXT, company TEXT, position TEXT, line_type TEXT, carrier TEXT, sources TEXT NOT NULL DEFAULT '{}', conflicts TEXT NOT NULL DEFAULT '[]', dismissed TEXT NOT NULL DEFAULT '[]', active_tool TEXT, org_status TEXT, org_note TEXT, theorg_slug TEXT, icp_fit TEXT, icp_reasons TEXT, company_li_id TEXT, open_positions TEXT, positions_checked_at INTEGER, outreach_lang TEXT, client_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, steps TEXT, company_staff_count INTEGER, company_context TEXT, company_checked_at INTEGER);
CREATE TABLE IF NOT EXISTS plugin_gtm_leads (id TEXT PRIMARY KEY, phone TEXT NOT NULL, normalized_phone TEXT, status TEXT NOT NULL DEFAULT 'new', source TEXT, batch_id TEXT, country TEXT, region TEXT, name TEXT, photo TEXT, socials TEXT NOT NULL DEFAULT '[]', linkedin TEXT, email TEXT, company TEXT, position TEXT, line_type TEXT, carrier TEXT, sources TEXT NOT NULL DEFAULT '{}', conflicts TEXT NOT NULL DEFAULT '[]', dismissed TEXT NOT NULL DEFAULT '[]', active_tool TEXT, org_status TEXT, org_note TEXT, theorg_slug TEXT, icp_fit TEXT, icp_reasons TEXT, company_li_id TEXT, open_positions TEXT, positions_checked_at INTEGER, outreach_lang TEXT, client_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, steps TEXT, company_staff_count INTEGER, company_context TEXT, company_checked_at INTEGER);
INSERT OR IGNORE INTO plugin_gtm_leads (id, phone, normalized_phone, status, source, batch_id, country, region, name, photo, socials, linkedin, email, company, position, line_type, carrier, sources, conflicts, dismissed, active_tool, org_status, org_note, theorg_slug, icp_fit, icp_reasons, company_li_id, open_positions, positions_checked_at, outreach_lang, client_id, created_at, updated_at, steps, company_staff_count, company_context, company_checked_at) SELECT id, phone, normalized_phone, status, source, batch_id, country, region, name, photo, socials, linkedin, email, company, position, line_type, carrier, sources, conflicts, dismissed, active_tool, org_status, org_note, theorg_slug, icp_fit, icp_reasons, company_li_id, open_positions, positions_checked_at, outreach_lang, client_id, created_at, updated_at, steps, company_staff_count, company_context, company_checked_at FROM gtm_leads;
DROP TABLE gtm_leads;
CREATE TABLE IF NOT EXISTS li_prospects (id TEXT PRIMARY KEY, urn_id TEXT, public_id TEXT, name TEXT NOT NULL, role TEXT, company TEXT, circle INTEGER, location TEXT, status TEXT NOT NULL DEFAULT 'active', step_index INTEGER NOT NULL DEFAULT 0, next_action_at INTEGER, fail_count INTEGER NOT NULL DEFAULT 0, source_search TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, sequence_json TEXT, accepted_at INTEGER, replied_at INTEGER);
CREATE TABLE IF NOT EXISTS plugin_gtm_li_prospects (id TEXT PRIMARY KEY, urn_id TEXT, public_id TEXT, name TEXT NOT NULL, role TEXT, company TEXT, circle INTEGER, location TEXT, status TEXT NOT NULL DEFAULT 'active', step_index INTEGER NOT NULL DEFAULT 0, next_action_at INTEGER, fail_count INTEGER NOT NULL DEFAULT 0, source_search TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, sequence_json TEXT, accepted_at INTEGER, replied_at INTEGER);
INSERT OR IGNORE INTO plugin_gtm_li_prospects (id, urn_id, public_id, name, role, company, circle, location, status, step_index, next_action_at, fail_count, source_search, created_at, updated_at, sequence_json, accepted_at, replied_at) SELECT id, urn_id, public_id, name, role, company, circle, location, status, step_index, next_action_at, fail_count, source_search, created_at, updated_at, sequence_json, accepted_at, replied_at FROM li_prospects;
DROP TABLE li_prospects;
CREATE TABLE IF NOT EXISTS gtm_org_people (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, company TEXT, node_id TEXT, parent_node_id TEXT, name TEXT, role TEXT, photo_url TEXT, report_count INTEGER, source TEXT NOT NULL DEFAULT 'theorg', created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_org_people (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, company TEXT, node_id TEXT, parent_node_id TEXT, name TEXT, role TEXT, photo_url TEXT, report_count INTEGER, source TEXT NOT NULL DEFAULT 'theorg', created_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_org_people (id, lead_id, company, node_id, parent_node_id, name, role, photo_url, report_count, source, created_at) SELECT id, lead_id, company, node_id, parent_node_id, name, role, photo_url, report_count, source, created_at FROM gtm_org_people;
DROP TABLE gtm_org_people;
CREATE TABLE IF NOT EXISTS gtm_outreach_angles (lead_id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_outreach_angles (lead_id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_outreach_angles (lead_id, payload, created_at, updated_at) SELECT lead_id, payload, created_at, updated_at FROM gtm_outreach_angles;
DROP TABLE gtm_outreach_angles;
CREATE TABLE IF NOT EXISTS outreach_cohort_members (lead_id TEXT PRIMARY KEY, chat_id TEXT, status TEXT NOT NULL DEFAULT 'active', step INTEGER NOT NULL DEFAULT 0, next_send_at INTEGER, last_sent_at INTEGER, last_sent_text TEXT, answered_at INTEGER, stop_reason TEXT, last_error TEXT, enrolled_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, cohort_id TEXT, approved_at INTEGER, approved_step INTEGER, approved_step_at INTEGER, override_text TEXT, override_step INTEGER);
CREATE TABLE IF NOT EXISTS plugin_gtm_outreach_cohort_members (lead_id TEXT PRIMARY KEY, chat_id TEXT, status TEXT NOT NULL DEFAULT 'active', step INTEGER NOT NULL DEFAULT 0, next_send_at INTEGER, last_sent_at INTEGER, last_sent_text TEXT, answered_at INTEGER, stop_reason TEXT, last_error TEXT, enrolled_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, cohort_id TEXT, approved_at INTEGER, approved_step INTEGER, approved_step_at INTEGER, override_text TEXT, override_step INTEGER);
INSERT OR IGNORE INTO plugin_gtm_outreach_cohort_members (lead_id, chat_id, status, step, next_send_at, last_sent_at, last_sent_text, answered_at, stop_reason, last_error, enrolled_at, updated_at, cohort_id, approved_at, approved_step, approved_step_at, override_text, override_step) SELECT lead_id, chat_id, status, step, next_send_at, last_sent_at, last_sent_text, answered_at, stop_reason, last_error, enrolled_at, updated_at, cohort_id, approved_at, approved_step, approved_step_at, override_text, override_step FROM outreach_cohort_members;
DROP TABLE outreach_cohort_members;
CREATE TABLE IF NOT EXISTS outreach_cohorts (id TEXT PRIMARY KEY, name TEXT NOT NULL, note TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, sequence TEXT, status TEXT NOT NULL DEFAULT 'active', timezone TEXT, send_days TEXT, languages TEXT, start_hour INTEGER, end_hour INTEGER, send_windows TEXT);
CREATE TABLE IF NOT EXISTS plugin_gtm_outreach_cohorts (id TEXT PRIMARY KEY, name TEXT NOT NULL, note TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, sequence TEXT, status TEXT NOT NULL DEFAULT 'active', timezone TEXT, send_days TEXT, languages TEXT, start_hour INTEGER, end_hour INTEGER, send_windows TEXT);
INSERT OR IGNORE INTO plugin_gtm_outreach_cohorts (id, name, note, created_at, updated_at, sequence, status, timezone, send_days, languages, start_hour, end_hour, send_windows) SELECT id, name, note, created_at, updated_at, sequence, status, timezone, send_days, languages, start_hour, end_hour, send_windows FROM outreach_cohorts;
DROP TABLE outreach_cohorts;
CREATE TABLE IF NOT EXISTS outreach_conversation_state (lead_id TEXT PRIMARY KEY, dead_at INTEGER, dead_reason TEXT, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_outreach_conversation_state (lead_id TEXT PRIMARY KEY, dead_at INTEGER, dead_reason TEXT, updated_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_outreach_conversation_state (lead_id, dead_at, dead_reason, updated_at) SELECT lead_id, dead_at, dead_reason, updated_at FROM outreach_conversation_state;
DROP TABLE outreach_conversation_state;
CREATE TABLE IF NOT EXISTS outreach_threads (key TEXT PRIMARY KEY, channel TEXT NOT NULL, name TEXT, replied INTEGER DEFAULT 0, uncaught INTEGER DEFAULT 0, msgs_in INTEGER DEFAULT 0, msgs_out INTEGER DEFAULT 0, last_inbound_text TEXT, last_inbound_at INTEGER, sentiment TEXT, sentiment_reason TEXT, sentiment_at INTEGER, updated_at INTEGER);
CREATE TABLE IF NOT EXISTS plugin_gtm_outreach_threads (key TEXT PRIMARY KEY, channel TEXT NOT NULL, name TEXT, replied INTEGER DEFAULT 0, uncaught INTEGER DEFAULT 0, msgs_in INTEGER DEFAULT 0, msgs_out INTEGER DEFAULT 0, last_inbound_text TEXT, last_inbound_at INTEGER, sentiment TEXT, sentiment_reason TEXT, sentiment_at INTEGER, updated_at INTEGER);
INSERT OR IGNORE INTO plugin_gtm_outreach_threads (key, channel, name, replied, uncaught, msgs_in, msgs_out, last_inbound_text, last_inbound_at, sentiment, sentiment_reason, sentiment_at, updated_at) SELECT key, channel, name, replied, uncaught, msgs_in, msgs_out, last_inbound_text, last_inbound_at, sentiment, sentiment_reason, sentiment_at, updated_at FROM outreach_threads;
DROP TABLE outreach_threads;
CREATE TABLE IF NOT EXISTS scheduled_sends (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, chat_id TEXT NOT NULL, bubbles TEXT NOT NULL, content_hash TEXT NOT NULL, send_at INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', claim_token TEXT, claimed_at INTEGER, sent_at INTEGER, error TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_scheduled_sends (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, chat_id TEXT NOT NULL, bubbles TEXT NOT NULL, content_hash TEXT NOT NULL, send_at INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', claim_token TEXT, claimed_at INTEGER, sent_at INTEGER, error TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_scheduled_sends (id, lead_id, chat_id, bubbles, content_hash, send_at, status, claim_token, claimed_at, sent_at, error, created_at, updated_at) SELECT id, lead_id, chat_id, bubbles, content_hash, send_at, status, claim_token, claimed_at, sent_at, error, created_at, updated_at FROM scheduled_sends;
DROP TABLE scheduled_sends;
CREATE TABLE IF NOT EXISTS gtm_sends (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, chat_id TEXT, bubble TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'sent', error TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_gtm_sends (id TEXT PRIMARY KEY, lead_id TEXT NOT NULL, chat_id TEXT, bubble TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'sent', error TEXT, created_at INTEGER NOT NULL);
INSERT OR IGNORE INTO plugin_gtm_sends (id, lead_id, chat_id, bubble, status, error, created_at) SELECT id, lead_id, chat_id, bubble, status, error, created_at FROM gtm_sends;
DROP TABLE gtm_sends;
CREATE TABLE IF NOT EXISTS wa_outreach_class (msg_id TEXT PRIMARY KEY, chat_id TEXT, is_outreach INTEGER NOT NULL, reason TEXT, classified_at INTEGER);
CREATE TABLE IF NOT EXISTS plugin_gtm_wa_outreach_class (msg_id TEXT PRIMARY KEY, chat_id TEXT, is_outreach INTEGER NOT NULL, reason TEXT, classified_at INTEGER);
INSERT OR IGNORE INTO plugin_gtm_wa_outreach_class (msg_id, chat_id, is_outreach, reason, classified_at) SELECT msg_id, chat_id, is_outreach, reason, classified_at FROM wa_outreach_class;
DROP TABLE wa_outreach_class;

-- Knowledge moves into the plugin namespace, operator edits preserved.
UPDATE knowledge_docs SET slug='plugin-gtm-api-limits' WHERE slug='gtm-api-limits' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-api-limits');
DELETE FROM knowledge_docs WHERE slug='gtm-api-limits';
UPDATE knowledge_docs SET slug='plugin-gtm-api-limits' WHERE slug='api-limits' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-api-limits');
DELETE FROM knowledge_docs WHERE slug='api-limits';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-cohort-cadence' WHERE slug='gtm-outreach-cohort-cadence' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-cohort-cadence');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-cohort-cadence';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-cohort-cadence' WHERE slug='outreach-cohort-cadence' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-cohort-cadence');
DELETE FROM knowledge_docs WHERE slug='outreach-cohort-cadence';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-first-touch' WHERE slug='gtm-outreach-first-touch' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-first-touch');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-first-touch';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-first-touch' WHERE slug='outreach-first-touch' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-first-touch');
DELETE FROM knowledge_docs WHERE slug='outreach-first-touch';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-promotion' WHERE slug='gtm-outreach-promotion' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-promotion');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-promotion';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-promotion' WHERE slug='outreach-promotion' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-promotion');
DELETE FROM knowledge_docs WHERE slug='outreach-promotion';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-reply-drafting' WHERE slug='gtm-outreach-reply-drafting' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-reply-drafting');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-reply-drafting';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-reply-drafting' WHERE slug='outreach-reply-drafting' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-reply-drafting');
DELETE FROM knowledge_docs WHERE slug='outreach-reply-drafting';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-sentiment' WHERE slug='gtm-outreach-sentiment' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-sentiment');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-sentiment';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-sentiment' WHERE slug='outreach-sentiment' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-sentiment');
DELETE FROM knowledge_docs WHERE slug='outreach-sentiment';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-signature' WHERE slug='gtm-outreach-signature' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-signature');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach-signature';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach-signature' WHERE slug='outreach-signature' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach-signature');
DELETE FROM knowledge_docs WHERE slug='outreach-signature';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach' WHERE slug='gtm-outreach' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach');
DELETE FROM knowledge_docs WHERE slug='gtm-outreach';
UPDATE knowledge_docs SET slug='plugin-gtm-outreach' WHERE slug='outreach' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-outreach');
DELETE FROM knowledge_docs WHERE slug='outreach';
UPDATE knowledge_docs SET slug='plugin-gtm-policy' WHERE slug='gtm-policy' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-policy');
DELETE FROM knowledge_docs WHERE slug='gtm-policy';
UPDATE knowledge_docs SET slug='plugin-gtm-policy' WHERE slug='policy' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-policy');
DELETE FROM knowledge_docs WHERE slug='policy';
UPDATE knowledge_docs SET slug='plugin-gtm-schedule' WHERE slug='gtm-schedule' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-schedule');
DELETE FROM knowledge_docs WHERE slug='gtm-schedule';
UPDATE knowledge_docs SET slug='plugin-gtm-schedule' WHERE slug='schedule' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-schedule');
DELETE FROM knowledge_docs WHERE slug='schedule';
UPDATE knowledge_docs SET slug='plugin-gtm-you' WHERE slug='gtm-you' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-you');
DELETE FROM knowledge_docs WHERE slug='gtm-you';
UPDATE knowledge_docs SET slug='plugin-gtm-you' WHERE slug='you' AND NOT EXISTS (SELECT 1 FROM knowledge_docs WHERE slug='plugin-gtm-you');
DELETE FROM knowledge_docs WHERE slug='you';

-- The host-seeded copies of the workflows now shipped BY the plugin: their
-- seed files are deleted, so the rows are orphans blocking the plugin's slugs.
DELETE FROM workflows WHERE slug='enrich-lead' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='company-context' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='qualify-lead' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='draft-outreach-angles' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='clean-identity' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='draft-prospect-reply' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='outreach-cohort-tick' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='outreach-replies-to-pipeline' AND created_by IN ('system','seed');
DELETE FROM workflows WHERE slug='scheduled-send-tick' AND created_by IN ('system','seed');
