// GENERATED by the Plugins module — do not edit by hand.
// Aggregates every installed plugin into the tool pool and gateway registry.
// Each plugin runs against a capability object (lib/plugin-runtime.js): a
// namespace-scoped DB, a gateway function closed over its own binding, and
// a namespaced logger. Plugin code never receives env.

import { pluginApi, wrapGatewayModes } from '../lib/plugin-runtime.js';
import * as p0 from './gtm/tool-approve_message.mjs';
import * as p1 from './gtm/tool-audit_identities.mjs';
import * as p2 from './gtm/tool-cancel_scheduled_send.mjs';
import * as p3 from './gtm/tool-collect_replies.mjs';
import * as p4 from './gtm/tool-company_context.mjs';
import * as p5 from './gtm/tool-compose_reply.mjs';
import * as p6 from './gtm/tool-create_cohort.mjs';
import * as p7 from './gtm/tool-delete_cohort.mjs';
import * as p8 from './gtm/tool-draft_angles.mjs';
import * as p9 from './gtm/tool-draft_prospect_reply.mjs';
import * as p10 from './gtm/tool-draft_step_copy.mjs';
import * as p11 from './gtm/tool-edit_lead.mjs';
import * as p12 from './gtm/tool-enrich_batch.mjs';
import * as p13 from './gtm/tool-enrich_lead.mjs';
import * as p14 from './gtm/tool-enrich_person_pdl.mjs';
import * as p15 from './gtm/tool-enroll_members.mjs';
import * as p16 from './gtm/tool-fetch_company_profile.mjs';
import * as p17 from './gtm/tool-fetch_open_roles.mjs';
import * as p18 from './gtm/tool-fetch_org_chart.mjs';
import * as p19 from './gtm/tool-gate_member_approvals.mjs';
import * as p20 from './gtm/tool-import_leads.mjs';
import * as p21 from './gtm/tool-launch_members.mjs';
import * as p22 from './gtm/tool-list_batches.mjs';
import * as p23 from './gtm/tool-list_cohort_members.mjs';
import * as p24 from './gtm/tool-list_cohorts.mjs';
import * as p25 from './gtm/tool-list_due_members.mjs';
import * as p26 from './gtm/tool-list_green_leads.mjs';
import * as p27 from './gtm/tool-list_leads.mjs';
import * as p28 from './gtm/tool-list_prospect_threads.mjs';
import * as p29 from './gtm/tool-list_scheduled_sends.mjs';
import * as p30 from './gtm/tool-lookup_company_from_linkedin.mjs';
import * as p31 from './gtm/tool-lookup_line_twilio.mjs';
import * as p32 from './gtm/tool-lookup_wa_identity.mjs';
import * as p33 from './gtm/tool-mark_thread_dead.mjs';
import * as p34 from './gtm/tool-override_message.mjs';
import * as p35 from './gtm/tool-pause_member.mjs';
import * as p36 from './gtm/tool-pick_next_bubble.mjs';
import * as p37 from './gtm/tool-promote_lead.mjs';
import * as p38 from './gtm/tool-promote_replies.mjs';
import * as p39 from './gtm/tool-qualify_lead.mjs';
import * as p40 from './gtm/tool-read_api_usage.mjs';
import * as p41 from './gtm/tool-read_cadence.mjs';
import * as p42 from './gtm/tool-read_drafting_rules.mjs';
import * as p43 from './gtm/tool-read_lead.mjs';
import * as p44 from './gtm/tool-read_lead_angles.mjs';
import * as p45 from './gtm/tool-read_promotion_rules.mjs';
import * as p46 from './gtm/tool-read_prospect_thread.mjs';
import * as p47 from './gtm/tool-read_sequence.mjs';
import * as p48 from './gtm/tool-read_you.mjs';
import * as p49 from './gtm/tool-reconcile_identity.mjs';
import * as p50 from './gtm/tool-remove_member.mjs';
import * as p51 from './gtm/tool-render_member_messages.mjs';
import * as p52 from './gtm/tool-reschedule_member.mjs';
import * as p53 from './gtm/tool-retire_answered_members.mjs';
import * as p54 from './gtm/tool-run_cohort_tick.mjs';
import * as p55 from './gtm/tool-run_due_sends.mjs';
import * as p56 from './gtm/tool-save_angles.mjs';
import * as p57 from './gtm/tool-save_cadence.mjs';
import * as p58 from './gtm/tool-save_drafting_rules.mjs';
import * as p59 from './gtm/tool-save_lead.mjs';
import * as p60 from './gtm/tool-save_org_chart.mjs';
import * as p61 from './gtm/tool-save_promotion_rules.mjs';
import * as p62 from './gtm/tool-save_sequence.mjs';
import * as p63 from './gtm/tool-schedule_send.mjs';
import * as p64 from './gtm/tool-score_icp.mjs';
import * as p65 from './gtm/tool-search_socials_serp.mjs';
import * as p66 from './gtm/tool-send_due_messages.mjs';
import * as p67 from './gtm/tool-send_outreach.mjs';
import * as p68 from './gtm/tool-send_prospect_message.mjs';
import * as p69 from './gtm/tool-stop_member.mjs';
import * as p70 from './gtm/tool-unschedule_member.mjs';
import * as p71 from './gtm/tool-update_api_limits.mjs';
import * as p72 from './gtm/tool-update_cohort.mjs';

const BINDINGS = {
  "gtm": {
    "assets": {
      "via": "host",
      "target": "assets",
      "modes": [
        "store"
      ]
    },
    "crm": {
      "via": "host",
      "target": "crm",
      "modes": [
        "promote",
        "update_deal",
        "write_contact"
      ]
    },
    "linkedin": {
      "via": "host",
      "target": "linkedin",
      "modes": [
        "company",
        "company_jobs"
      ]
    },
    "llm": {
      "via": "host",
      "target": "llm",
      "modes": [
        "text"
      ]
    },
    "pdl": {
      "via": "host",
      "target": "pdl",
      "modes": [
        "person"
      ]
    },
    "serp": {
      "via": "host",
      "target": "serp",
      "modes": [
        "search"
      ]
    },
    "theorg": {
      "via": "host",
      "target": "theorg",
      "modes": [
        "org_chart",
        "probe"
      ]
    },
    "twilio": {
      "via": "host",
      "target": "twilio",
      "modes": [
        "lookup"
      ]
    },
    "web": {
      "via": "host",
      "target": "web",
      "modes": [
        "bytes",
        "text"
      ]
    },
    "whatsapp": {
      "via": "host",
      "target": "whatsapp",
      "modes": [
        "backfill_messages",
        "contact",
        "group_info",
        "resolve_lids",
        "send",
        "set_listening"
      ]
    }
  }
};
const TABLES = {
  "gtm": [
    "plugin_gtm_api_quota",
    "plugin_gtm_api_usage",
    "plugin_gtm_batches",
    "plugin_gtm_leads",
    "plugin_gtm_li_prospects",
    "plugin_gtm_org_people",
    "plugin_gtm_outreach_angles",
    "plugin_gtm_outreach_cohort_members",
    "plugin_gtm_outreach_cohorts",
    "plugin_gtm_outreach_conversation_state",
    "plugin_gtm_outreach_threads",
    "plugin_gtm_scheduled_sends",
    "plugin_gtm_sends",
    "plugin_gtm_wa_outreach_class"
  ]
};
const KNOWLEDGE = {
  "gtm": [
    "llm-models"
  ]
};
const HOST_READS = {
  "gtm": [
    "clients",
    "contacts",
    "feature_flags",
    "wa_chats",
    "wa_lid_map",
    "wa_messages"
  ]
};

export const pluginTools = {
  "approve_message": { def: p0.def, run: (env, input, ctx) => p0.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "audit_identities": { def: p1.def, run: (env, input, ctx) => p1.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "cancel_scheduled_send": { def: p2.def, run: (env, input, ctx) => p2.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "collect_replies": { def: p3.def, run: (env, input, ctx) => p3.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "company_context": { def: p4.def, run: (env, input, ctx) => p4.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "compose_reply": { def: p5.def, run: (env, input, ctx) => p5.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "create_cohort": { def: p6.def, run: (env, input, ctx) => p6.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "delete_cohort": { def: p7.def, run: (env, input, ctx) => p7.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "draft_angles": { def: p8.def, run: (env, input, ctx) => p8.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "draft_prospect_reply": { def: p9.def, run: (env, input, ctx) => p9.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "draft_step_copy": { def: p10.def, run: (env, input, ctx) => p10.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "edit_lead": { def: p11.def, run: (env, input, ctx) => p11.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "enrich_batch": { def: p12.def, run: (env, input, ctx) => p12.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "enrich_lead": { def: p13.def, run: (env, input, ctx) => p13.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "enrich_person_pdl": { def: p14.def, run: (env, input, ctx) => p14.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "enroll_members": { def: p15.def, run: (env, input, ctx) => p15.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "fetch_company_profile": { def: p16.def, run: (env, input, ctx) => p16.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "fetch_open_roles": { def: p17.def, run: (env, input, ctx) => p17.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "fetch_org_chart": { def: p18.def, run: (env, input, ctx) => p18.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "gate_member_approvals": { def: p19.def, run: (env, input, ctx) => p19.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "import_leads": { def: p20.def, run: (env, input, ctx) => p20.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "launch_members": { def: p21.def, run: (env, input, ctx) => p21.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_batches": { def: p22.def, run: (env, input, ctx) => p22.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_cohort_members": { def: p23.def, run: (env, input, ctx) => p23.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_cohorts": { def: p24.def, run: (env, input, ctx) => p24.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_due_members": { def: p25.def, run: (env, input, ctx) => p25.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_green_leads": { def: p26.def, run: (env, input, ctx) => p26.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_leads": { def: p27.def, run: (env, input, ctx) => p27.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_prospect_threads": { def: p28.def, run: (env, input, ctx) => p28.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "list_scheduled_sends": { def: p29.def, run: (env, input, ctx) => p29.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "lookup_company_from_linkedin": { def: p30.def, run: (env, input, ctx) => p30.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "lookup_line_twilio": { def: p31.def, run: (env, input, ctx) => p31.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "lookup_wa_identity": { def: p32.def, run: (env, input, ctx) => p32.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "mark_thread_dead": { def: p33.def, run: (env, input, ctx) => p33.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "override_message": { def: p34.def, run: (env, input, ctx) => p34.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "pause_member": { def: p35.def, run: (env, input, ctx) => p35.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "pick_next_bubble": { def: p36.def, run: (env, input, ctx) => p36.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "promote_lead": { def: p37.def, run: (env, input, ctx) => p37.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "promote_replies": { def: p38.def, run: (env, input, ctx) => p38.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "qualify_lead": { def: p39.def, run: (env, input, ctx) => p39.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_api_usage": { def: p40.def, run: (env, input, ctx) => p40.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_cadence": { def: p41.def, run: (env, input, ctx) => p41.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_drafting_rules": { def: p42.def, run: (env, input, ctx) => p42.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_lead": { def: p43.def, run: (env, input, ctx) => p43.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_lead_angles": { def: p44.def, run: (env, input, ctx) => p44.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_promotion_rules": { def: p45.def, run: (env, input, ctx) => p45.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_prospect_thread": { def: p46.def, run: (env, input, ctx) => p46.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_sequence": { def: p47.def, run: (env, input, ctx) => p47.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "read_you": { def: p48.def, run: (env, input, ctx) => p48.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "reconcile_identity": { def: p49.def, run: (env, input, ctx) => p49.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "remove_member": { def: p50.def, run: (env, input, ctx) => p50.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "render_member_messages": { def: p51.def, run: (env, input, ctx) => p51.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "reschedule_member": { def: p52.def, run: (env, input, ctx) => p52.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "retire_answered_members": { def: p53.def, run: (env, input, ctx) => p53.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "run_cohort_tick": { def: p54.def, run: (env, input, ctx) => p54.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "run_due_sends": { def: p55.def, run: (env, input, ctx) => p55.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_angles": { def: p56.def, run: (env, input, ctx) => p56.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_cadence": { def: p57.def, run: (env, input, ctx) => p57.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_drafting_rules": { def: p58.def, run: (env, input, ctx) => p58.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_lead": { def: p59.def, run: (env, input, ctx) => p59.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_org_chart": { def: p60.def, run: (env, input, ctx) => p60.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_promotion_rules": { def: p61.def, run: (env, input, ctx) => p61.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "save_sequence": { def: p62.def, run: (env, input, ctx) => p62.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "schedule_send": { def: p63.def, run: (env, input, ctx) => p63.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "score_icp": { def: p64.def, run: (env, input, ctx) => p64.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "search_socials_serp": { def: p65.def, run: (env, input, ctx) => p65.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "send_due_messages": { def: p66.def, run: (env, input, ctx) => p66.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "send_outreach": { def: p67.def, run: (env, input, ctx) => p67.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "send_prospect_message": { def: p68.def, run: (env, input, ctx) => p68.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "stop_member": { def: p69.def, run: (env, input, ctx) => p69.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "unschedule_member": { def: p70.def, run: (env, input, ctx) => p70.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "update_api_limits": { def: p71.def, run: (env, input, ctx) => p71.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
  "update_cohort": { def: p72.def, run: (env, input, ctx) => p72.run(pluginApi(env, "gtm", BINDINGS["gtm"], TABLES["gtm"], KNOWLEDGE["gtm"], HOST_READS["gtm"]), input, ctx) },
};

export const pluginGateways = {
};
