// GENERATED by the Plugins module — do not edit by hand.
// Aggregates every installed plugin into the tool pool and gateway registry.
// A fresh install has none; the applier regenerates this file whenever a
// plugin is imported or removed.

export const pluginTools = {};

export const pluginGateways = {};
