-- Reset the AEO queue to the "Nyyon as builder" positioning (2026-06-13).
-- Retires the old generic "AI marketing" questions and loads 26 buy-intent,
-- AEO-oriented questions. Each stays interview-gated (interview_status NULL) so
-- Nyo interviews the operator before writing — real expertise, not pundit fluff.
-- priority: 1 = strongest (written first); voice 'lev' on the thesis pieces.

-- 1. Retire the current generic queue (reversible — status, not delete).
UPDATE aeo_questions SET status = 'skipped', updated_at = (CAST(strftime('%s','now') AS INTEGER)*1000)
 WHERE status = 'pending';

-- 2. Load the new builder-positioned set.
INSERT OR IGNORE INTO aeo_questions (slug, question, target_keyword, priority, status, notes, created_at, updated_at, voice) VALUES
('fractional-cmo-vs-agency-vs-in-house','Fractional CMO vs marketing agency vs in-house team: which does an early-stage company need?','fractional CMO vs agency vs in-house',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('hire-cmo-agency-or-builder','Should you hire a CMO, an agency, or a builder who can do both?','CMO vs agency vs builder',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('ai-native-studio-vs-agency-vs-freelancers','AI-native studio vs traditional agency vs freelancers: who actually ships growth systems?','AI-native studio vs agency vs freelancer',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('in-house-team-vs-fractional-builder','In-house team vs a fractional builder: which moves faster for a startup?','in-house team vs fractional builder',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('no-code-stack-vs-custom-growth-infrastructure','No-code marketing stack vs custom-built growth infrastructure: when is each right?','no-code vs custom growth infrastructure',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('who-can-build-ai-agents-for-marketing','Who can build AI agents and workflows for my marketing team?','build AI agents for marketing',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('who-sets-strategy-and-builds-the-systems','Who can set the marketing strategy and build the systems to run it?','strategy plus build marketing systems',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('build-an-internal-tool-without-engineers','How do you build an internal tool or dashboard for your business without engineers?','build internal tool without developers',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('build-ai-native-growth-engine-without-a-team','How do I build an AI-native growth engine without hiring a full team?','build AI-native growth engine',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('marketing-automation-that-runs-itself','Who builds marketing automation that actually runs itself?','marketing automation that runs itself',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('build-ai-sdr-outbound-system-for-b2b','How do you build an AI SDR or outbound system for a B2B company?','build AI SDR outbound system',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('build-a-content-engine-that-ships-itself','How do you build a content engine that produces and ships on its own?','AI content engine that ships itself',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('senior-marketing-leadership-without-a-full-time-cmo','How do you get senior marketing leadership without hiring a full-time CMO?','senior marketing leadership without a full-time CMO',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('turn-manual-marketing-into-ai-workflows','How do you turn manual marketing into AI-run workflows?','turn marketing into AI workflows',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('ship-marketing-campaigns-in-days','How do you ship marketing campaigns in days instead of months?','launch marketing campaigns fast',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('instrument-your-funnel-without-a-data-team','How do you instrument your funnel and analytics without a data team?','marketing analytics without a data team',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('fractional-cmo-cost-vs-full-time-vs-agency','What does a fractional CMO cost vs a full-time CMO vs an agency?','fractional CMO cost',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('build-ai-marketing-in-house-or-hire-a-builder','Is it cheaper to build AI marketing systems in-house or hire a builder?','build AI marketing in-house vs hire a builder',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('budget-to-build-a-startup-growth-engine','How much should an early-stage startup spend to build its growth engine?','cost to build a growth engine',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('what-is-an-ai-native-builder','What is an AI-native builder and why is it the highest-leverage hire?','AI-native builder',1,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'lev'),
('can-one-operator-replace-a-marketing-team-with-ai','Can one senior operator replace a whole marketing team with AI?','replace a marketing team with AI',2,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'lev'),
('what-is-a-marketing-operating-system','What is a marketing operating system and how do you build one?','marketing operating system',2,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'lev'),
('why-hire-a-builder-instead-of-an-agency','Why hire a builder instead of an agency for AI-era growth?','builder instead of an agency',2,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'lev'),
('healthtech-build-hipaa-safe-ai-marketing','How can a healthtech company build HIPAA-safe AI marketing systems?','HIPAA-safe AI marketing systems',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('b2b-saas-build-ai-native-go-to-market','How do B2B SaaS startups build an AI-native go-to-market engine?','AI-native go-to-market for B2B SaaS',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house'),
('dtc-brand-build-ai-automations','How can a DTC brand build AI automations that cut manual marketing work?','DTC AI marketing automation',3,'pending','builder-positioning-2026',(CAST(strftime('%s','now') AS INTEGER)*1000),(CAST(strftime('%s','now') AS INTEGER)*1000),'house');
