#!/usr/bin/env node
// One command to a running command center.
//
//   npm run setup     (then: npm start)
//
// Deliberately needs NO Cloudflare account. The worker runs locally against a
// SQLite file and the SPA runs on Vite, so the first thing a new operator sees
// is the app, not a signup form. Deploying to Cloudflare is a separate, later
// choice (npm run deploy) — and it is the only way scheduled work runs, since
// cron triggers do not fire locally.
//
// Everything here is idempotent: re-running repairs a half-finished install
// rather than starting a second one.

import { execFileSync, execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const api = join(repo, 'workers', 'api');
const web = join(repo, 'web');
// Bundled external services. Not nyyon-lite gateways — those are the worker
// code that TALKS to these — but separate daemons the desktop shell runs
// alongside the worker, so WhatsApp works on a fresh install with nothing for
// the operator to find, host or tunnel.
const waService = join(repo, 'services', 'whatsapp');

let step = 0;
const say = (msg) => console.log(`\x1b[32m✓\x1b[0m ${msg}`);
const head = (msg) => console.log(`\n\x1b[1m${++step}. ${msg}\x1b[0m`);
const die = (msg, fix) => {
  console.error(`\n\x1b[31m✗ ${msg}\x1b[0m`);
  if (fix) console.error(`  ${fix}`);
  process.exit(1);
};

const run = (cmd, args, cwd, quiet = true) =>
  execFileSync(cmd, args, { cwd, encoding: 'utf8', stdio: quiet ? 'pipe' : 'inherit', maxBuffer: 64 * 1024 * 1024 });

// ── 1. the runtime ──────────────────────────────────────────────────────────
head('Checking Node');
const major = Number(process.versions.node.split('.')[0]);
if (major < 20) die(`Node ${process.versions.node} is too old.`, 'Install Node 20 or newer: https://nodejs.org');
say(`Node ${process.versions.node}`);

// ── 2. dependencies ─────────────────────────────────────────────────────────
head('Installing dependencies (this is the slow part)');
// The ROOT install is not optional and is easy to forget: Electron and the
// packager live in the root package.json, so without it `npm run package`
// fails and the operator never gets a desktop app — only a browser tab, which
// is not what this product is.
// The WhatsApp service is deliberately NOT in this list. Its dependency is
// whatsapp-web.js, which pulls Puppeteer and ~525 MB of Chromium — more than
// everything else here combined, and pure waste for the many people who never
// open Outreach. It is installed on demand instead, the first time somebody
// actually asks to connect WhatsApp (desktop/main.cjs, service:install). Its
// KEY is still generated below, because that costs nothing and means the
// connection is already paired when the install does happen.
for (const [label, dir] of [['worker', api], ['web app', web], ['desktop app', repo]]) {
  if (!existsSync(join(dir, 'package.json'))) die(`${label}: no package.json at ${dir}`);
  process.stdout.write(`   ${label}… `);
  try { run('npm', ['install', '--no-audit', '--no-fund'], dir); }
  catch (e) { die(`npm install failed for the ${label}.`, String(e.stderr || e.message).slice(0, 400)); }
  console.log('done');
}
say('dependencies installed');

// ── 3. local secrets ────────────────────────────────────────────────────────
// The gate secret signs session cookies and MUST be unique per install: a
// shipped default would let anyone forge a session on every copy of this app.
// No admin credentials are written — the onboarding conversation creates the
// account, so nobody starts with a known login.
head('Generating local config');
const devVars = join(api, '.dev.vars');
if (existsSync(devVars) && /^GATE_SECRET=.+/m.test(readFileSync(devVars, 'utf8'))) {
  say('.dev.vars already has a gate secret, left alone');
} else {
  const existing = existsSync(devVars) ? readFileSync(devVars, 'utf8').replace(/\s*$/, '') + '\n' : '';
  writeFileSync(devVars, `${existing}# Generated by scripts/setup.mjs. Gitignored — never commit this file.
# Unique to this install: it signs your session cookies.
GATE_SECRET=${randomBytes(32).toString('hex')}

# Your model key can go here, but it is easier to paste it into the setup
# screen on first run — it is stored in the database either way.
# ANTHROPIC_API_KEY=
`);
  say('.dev.vars written with a fresh gate secret');
}

// The WhatsApp service and the worker have to agree on one key, and the
// operator should never see it. Generate it once, write it to BOTH sides, and
// the connection is already made the first time the app opens — "connect
// WhatsApp" then means scanning a QR code, not finding a URL and a key for a
// daemon nobody has heard of.
//
// Same reasoning as GATE_SECRET: per install, never a shipped constant. The
// service refuses to boot without it (services/whatsapp/src/config.js).
// Idempotency has to consider BOTH files, not just the worker's. An install
// that already had a WA_API_KEY (an upgrade, or an operator who once pointed
// this at a gateway of their own) would otherwise be declared "already set"
// while the service side was never written — leaving a daemon that refuses to
// boot and a Connect button that never goes green.
// The plugin applier's key. Same per-install discipline as GATE_SECRET: the
// applier sidecar reads it from .dev.vars and the worker's gate compares
// against it, so without this a code-bearing plugin sits at `bound` forever
// while every applier call 401s — the whole subsystem dead on a real install.
{
  const text = existsSync(devVars) ? readFileSync(devVars, 'utf8') : '';
  if (!/^NYYON_APPLIER_KEY=.+/m.test(text)) {
    writeFileSync(devVars, `${text.replace(/\s*$/, '')}\n\n# Shared with the plugin applier (services/plugins/apply.mjs).\nNYYON_APPLIER_KEY=${randomBytes(24).toString('hex')}\n`);
    say('plugin applier key generated');
  }
}

const waEnv = join(waService, '.dev.vars');
const devVarsText = existsSync(devVars) ? readFileSync(devVars, 'utf8') : '';
const priorKey = /^WA_API_KEY=(.+)$/m.exec(devVarsText)?.[1]?.trim();

if (priorKey && existsSync(waEnv)) {
  say('WhatsApp service already paired, left alone');
} else {
  // Reuse a key the worker already has, so an existing setup keeps working;
  // only mint one when there is nothing to preserve.
  const waKey = priorKey || randomBytes(24).toString('hex');
  if (!priorKey) {
    // Worker side: read by the whatsapp gateway (workers/api/src/gateways).
    writeFileSync(devVars, `${devVarsText.replace(/\s*$/, '')}\n\n# Shared with the bundled WhatsApp service (services/whatsapp).\nWA_API_KEY=${waKey}\n`);
  }
  // Service side: the same key, as the daemon's own API_KEY.
  writeFileSync(waEnv, `# Generated by scripts/setup.mjs. Gitignored — never commit this file.\n# Must match WA_API_KEY in workers/api/.dev.vars.\nAPI_KEY=${waKey}\nPORT=2785\nSESSION_ID=default\n`);
  say(priorKey ? 'WhatsApp service paired using the existing key' : 'WhatsApp service paired with the worker');
}

// ── 4. the SPA bundle ───────────────────────────────────────────────────────
// The worker's assets binding points at web/dist, which is gitignored — on a
// clean clone it does not exist and wrangler refuses to start at all. Building
// once here fixes that AND proves the build works before the operator ever
// runs it. Vite serves the live SPA in dev; this bundle is what deploys.
head('Building the web app');
try { run('npm', ['run', 'build'], web); say('web/dist built'); }
catch (e) { die('the web build failed.', String(e.stdout || e.stderr || e.message).slice(-500)); }

// ── 5. the database ─────────────────────────────────────────────────────────
head('Building the local database');
const wrangler = (args, quiet = true) => run('npx', ['wrangler', ...args], api, quiet);

const migrations = execSync('ls db/migrations/*.sql | sort', { cwd: repo, encoding: 'utf8' })
  .trim().split('\n').filter(Boolean);

let applied = 0;
const failures = [];
for (const file of [join(repo, 'db', 'schema.sql'), ...migrations.map((m) => join(repo, m))]) {
  try { wrangler(['d1', 'execute', 'nyyon', '--local', '--file', file]); applied++; }
  catch (e) {
    // "already exists" / "duplicate column" mean a re-run over an existing
    // database, which is the idempotent path, not a failure.
    const out = String(e.stdout || '') + String(e.stderr || '');
    if (/already exists|duplicate column/i.test(out)) applied++;
    else failures.push(`${file.split('/').pop()}: ${(out.match(/ERROR[^\n]*/) || ['failed'])[0].slice(0, 120)}`);
  }
}
if (failures.length > 2) die(`${failures.length} migrations failed.`, failures.slice(0, 3).join('\n  '));
say(`schema + ${applied - 1} migrations applied${failures.length ? ` (${failures.length} skipped)` : ''}`);

// ── 6. what ships with the product ──────────────────────────────────────────
head('Seeding workflows and knowledge');
const tmp = mkdtempSync(join(tmpdir(), 'nyyon-setup-'));
for (const [label, script, args] of [
  ['workflows', 'seed-workflows.mjs', []],
  ['knowledge docs', 'seed-app.mjs', ['--docs-only']],
]) {
  const sql = join(tmp, `${label.replace(/\s/g, '-')}.sql`);
  writeFileSync(sql, run('node', [join('scripts', script), ...args], repo));
  try { wrangler(['d1', 'execute', 'nyyon', '--local', '--file', sql]); say(label); }
  catch (e) { die(`seeding ${label} failed.`, String(e.stderr || e.message).slice(0, 300)); }
}

// ── done ────────────────────────────────────────────────────────────────────
console.log(`
\x1b[1m\x1b[32mReady.\x1b[0m

  npm start

Then open \x1b[4mhttp://localhost:5180\x1b[0m. Setup is two screens — create your
account, connect a model — and you are in the app. Everything else (your
voice, your sources, WhatsApp, LinkedIn) is asked for by the module that
needs it, the first time you open it.

Note: scheduled work (queued sends, the hourly awareness sweep, the daily
writer) only runs once deployed to Cloudflare — cron triggers do not fire
locally. Everything you drive by hand works exactly as it will in production.
`);
