// GENERATED by the Plugins module — do not edit by hand.
// Maps 'plugin:<name>:<slug>' nav keys to installed plugins' pages.
import { lazy } from 'react';
export const PLUGIN_PAGES: Record<string, ReturnType<typeof lazy>> = {
};
